Create Table tblRSVP
(
rsvpID uniqueidentifier primary key default(newid()) not null,
hasRSVPed bit default(0) not null,
isAttending bit default(0) not null,
numPeopleAttending int default(0)not null,
namesOfPeopleAttending nvarchar(max),
rsvpComment nvarchar(max)
);


Create Table tblGuests
(
guestID uniqueidentifier primary key default(newid()) not null,
rsvpID uniqueidentifier not null foreign key references tblRSVP(rsvpID),
firstName nvarchar(255),
lastName nvarchar(255),
sortOrderInRsvp int null default(null)
);

declare @newID uniqueidentifier = newid();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Leslie', 'Anderson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Derek, Amy & Family', 'Anglemyer');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Paul, Karla & Family', 'Bauer');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jason, Erin & Marina', 'Beck');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'James, Elizabeth & Family', 'Bild');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kurt & Joan', 'Blevins');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kegan', 'Bohannon');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kwin, Sarah & Braylee', 'Bromley');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Max, Nichole & Oliver', 'Caldwell');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Andrew', 'Cardinez');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Eric', 'Cardinez');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Andrew & Soccorro', 'Cardinez');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'David', 'Chidyllo');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Dr. & Rochelle', 'Chronister');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tom & Francie', 'Currie');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Christina', 'D''Angelo');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jeff', 'D''Blay');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Heather', 'Dixon');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tim', 'Doak');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Lindsay', 'Dodge');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Terry & Mary', 'Downing');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Nick, Hannah & Gabe', 'Duetham');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Zach', 'Earnest');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Mary', 'Garcia');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Dan & Mary Carol', 'Garrity');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Shane, Kelli & Family', 'George');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Randy & Molly', 'Gildart');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Sara', 'Gonzales');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Rick & Judy', 'Green');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Malcom & Gail', 'Griffin');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Nina', 'Gruber');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Max', 'Gruber');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Christopher', 'Guidarelli');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'John & Susan', 'Gutchenritter');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kelly', 'Halverson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Doug & Becky', 'Hamer');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kyle', 'Hamer');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Gail', 'Hanson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Terry & JoAnne', 'Harper');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Paige', 'Hebard');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tim, Diana & Cora', 'Herman');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Patrick, Deedra & Family', 'Herrera');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jeremy, Sheri & Family', 'Huguenin');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Valon & Alex', 'Jones');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Crystal', 'Julian');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Sarah', 'Kersey');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Danny & Martha', 'Koehler');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Bruce, Krystan & Family', 'Koehn');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Patrick & Ginger', 'Krueger');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Ryan, Nicole & Family', 'Krueger');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Matthew, Alyssa & Isla', 'Krueger');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Brenden, Jill & Family', 'Krueger');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Casey & Julie', 'Lair');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Bill & Carol', 'Lark');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Troy & Jennette', 'Lark');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Travis, Allison & Family', 'Lark');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Mike & Teresa', 'Lee');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'David', 'Lee');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tony', 'Lee');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Emily', 'Lenney');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tyler, Kally & Owen', 'Lewis');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jeanie', 'Lynch');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Will, Tara & Family', 'Mann');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Caitlin', 'Mantica');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jake, Heather & Rhyder', 'Martin');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Dom & Pat', 'Martino');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Sally', 'Marure');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Moses', 'Marure');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Beto', 'Marure');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tim, Kim & Family', 'Milas');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'David & Yolanda', 'Morales');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Ryan & Paige', 'Morales');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Justin', 'Mullikin');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'David & Nancy', 'Nickerbocker');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Erin', 'Peeny');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Sophie', 'Peitz');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Gerald & Pat', 'Penning');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Amber', 'Phillips');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Linda', 'Ryburn');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Chelsea, Ben & Family', 'Schmidt');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kevin, Breann & Emersyn', 'Schoon');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Caleb & Lindsay', 'Schroeder');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Keaton, Abbee & Asher', 'Schultz');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Gary & Karolyn', 'Schultz');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Niles & Beth', 'Schurle');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Christopher', 'Sellers');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kent & Sandy', 'Shields');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jeff & Carol', 'Smith');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Dan, Brittaney & Family', 'Stapleton');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Carol Dean', 'Thomison');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Irene', 'Wade');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kara', 'Wade');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kelby, Allison & Sadie', 'Wadkins');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Troy, Lynlie & Family', 'Wallach');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kate', 'Walsh');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Lana & Family', 'White');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Randy & Tammy', 'White');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Jim & Connie', 'Wietharn');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Clark & Kelli', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Pat & Cheryl', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kyle & Monica', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Keith, Jacqui & Delanry', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Kevin & Melanie', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Tim, Anna Marie & Family', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Seth', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Samantha & Sloane', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Angie', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Hal, Holly & Brianna', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Audrey', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Chelsea', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Terry & Laurie', 'Wilson');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Mark & Cyressa', 'Windsor');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'Chris, Kate & Hannah', 'Woll');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName) VALUES (@newID, 'John', 'Zamojski');
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Sam', 'Gruber', 1);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Laura', 'Marrocco', 2);
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Joe', 'Underwood', 1);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Mark', 'Weatherby', 2);
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Erica', 'Wilson', 1);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Kyle', 'Martin', 2);
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Al', 'Wilson', 1);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Paul', 'Warner', 2);
set @newID = newID();
insert into tblrsvp (rsvpID) VALUES(@newID);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Kelly', 'Wilson', 1);
insert into tblGuests (rsvpID, firstName, lastName, sortOrderInRsvp) VALUES (@newID, 'Jerry', 'Malach', 2);
